# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-10-27 03:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grading_code', '0002_classroom_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='class_name',
            new_name='classroom',
        ),
    ]
